# Generated by Django 5.2.16 on 2026-07-27 04:18

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("knowledge", "0001_enable_vector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source_id",
                    models.PositiveIntegerField(
                        help_text="Identificador da fonte em data/normas/fontes.json.", unique=True
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("institution", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=500)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("regulamento-auditorio", "Regulamento de auditório"),
                            ("resolucao-institucional", "Resolução institucional"),
                            ("procedimento-reserva", "Procedimento de reserva"),
                            ("contexto-juridico", "Contexto jurídico"),
                            ("complementar-internacional", "Complementar internacional"),
                        ],
                        default="regulamento-auditorio",
                        max_length=40,
                    ),
                ),
                ("source_url", models.URLField(max_length=1000)),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("html", "HTML"), ("txt", "Texto")], max_length=10
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        help_text="SHA-256 do arquivo. Permite reprocessar apenas o que mudou.",
                        max_length=64,
                    ),
                ),
                ("word_count", models.PositiveIntegerField(default=0)),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["source_id"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        help_text="Ordem do trecho dentro do documento, começando em zero."
                    ),
                ),
                ("text", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=384)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
                ),
                ("word_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="knowledge.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trecho",
                "verbose_name_plural": "Trechos",
                "ordering": ["document", "position"],
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="chunk_embedding_hnsw",
                        opclasses=["vector_cosine_ops"],
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="chunk_search_vector_gin"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "position"), name="unique_chunk_position_per_document"
                    )
                ],
            },
        ),
    ]
