# Generated by Django 5.2.16 on 2026-07-27 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                (
                    "sources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Cópia dos trechos citados, preservada mesmo após reindexação.",
                    ),
                ),
                ("used_context", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_turns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Turno de conversa",
                "verbose_name_plural": "Turnos de conversa",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="turn_user_recent_idx")
                ],
            },
        ),
    ]
