"""URL configuration for admin_dashboard app."""

from django.urls import path

from .views import (
    AdminAttributeCreateView,
    AdminAttributeListView,
    AdminAttributeUpdateView,
    AdminBookingPolicyView,
    AdminCalendarView,
    AdminDashboardView,
    AdminHelpArticleCreateView,
    AdminHelpArticleDeleteView,
    AdminHelpArticleListView,
    AdminHelpArticleUpdateView,
    AdminMaintenanceClassifyView,
    AdminMaintenanceCreateView,
    AdminMaintenanceDeleteView,
    AdminMaintenanceListView,
    AdminReportsCsvView,
    AdminReportsView,
    AdminReservationCancelView,
    AdminReservationListView,
    AdminServiceQueueView,
    AdminServiceRequestUpdateView,
    AdminServiceTypeCreateView,
    AdminServiceTypeListView,
    AdminServiceTypeUpdateView,
    AdminSpaceCreateView,
    AdminSpaceListView,
    AdminSpaceToggleView,
    AdminSpaceTypeCreateView,
    AdminSpaceTypeListView,
    AdminSpaceTypeUpdateView,
    AdminSpaceUpdateView,
    AdminUserCreateView,
    AdminUserDeleteView,
    AdminUserListView,
    AdminUserUpdateView,
)

app_name = "admin_dashboard"

urlpatterns = [
    path("", AdminDashboardView.as_view(), name="admin_dashboard"),
    path("calendario/", AdminCalendarView.as_view(), name="calendar"),
    path("relatorios/", AdminReportsView.as_view(), name="reports"),
    path("relatorios/csv/", AdminReportsCsvView.as_view(), name="reports_csv"),
    path("spaces/", AdminSpaceListView.as_view(), name="space_list"),
    path("spaces/new/", AdminSpaceCreateView.as_view(), name="space_create"),
    path("spaces/<int:pk>/", AdminSpaceUpdateView.as_view(), name="space_update"),
    path("spaces/<int:pk>/toggle/", AdminSpaceToggleView.as_view(), name="space_toggle"),
    path("space-types/", AdminSpaceTypeListView.as_view(), name="space_type_list"),
    path("space-types/new/", AdminSpaceTypeCreateView.as_view(), name="space_type_create"),
    path("space-types/<int:pk>/", AdminSpaceTypeUpdateView.as_view(), name="space_type_update"),
    path("attributes/", AdminAttributeListView.as_view(), name="attribute_list"),
    path("attributes/new/", AdminAttributeCreateView.as_view(), name="attribute_create"),
    path("attributes/<int:pk>/", AdminAttributeUpdateView.as_view(), name="attribute_update"),
    path("services/", AdminServiceTypeListView.as_view(), name="service_type_list"),
    path("services/new/", AdminServiceTypeCreateView.as_view(), name="service_type_create"),
    path("services/<int:pk>/", AdminServiceTypeUpdateView.as_view(), name="service_type_update"),
    path("service-requests/", AdminServiceQueueView.as_view(), name="service_queue"),
    path(
        "service-requests/<int:pk>/status/",
        AdminServiceRequestUpdateView.as_view(),
        name="service_request_update",
    ),
    path("policy/", AdminBookingPolicyView.as_view(), name="booking_policy"),
    path("ajuda/", AdminHelpArticleListView.as_view(), name="help_article_list"),
    path("ajuda/new/", AdminHelpArticleCreateView.as_view(), name="help_article_create"),
    path(
        "ajuda/<int:pk>/",
        AdminHelpArticleUpdateView.as_view(),
        name="help_article_update",
    ),
    path(
        "ajuda/<int:pk>/delete/",
        AdminHelpArticleDeleteView.as_view(),
        name="help_article_delete",
    ),
    path("reservations/", AdminReservationListView.as_view(), name="reservation_list"),
    path(
        "reservations/<int:pk>/cancel/",
        AdminReservationCancelView.as_view(),
        name="reservation_cancel",
    ),
    path(
        "maintenance/",
        AdminMaintenanceListView.as_view(),
        name="maintenance_list",
    ),
    path(
        "maintenance/new/",
        AdminMaintenanceCreateView.as_view(),
        name="maintenance_create",
    ),
    path(
        "maintenance/classify/",
        AdminMaintenanceClassifyView.as_view(),
        name="maintenance_classify",
    ),
    path(
        "maintenance/<int:pk>/delete/",
        AdminMaintenanceDeleteView.as_view(),
        name="maintenance_delete",
    ),
    path("users/", AdminUserListView.as_view(), name="user_list"),
    path("users/new/", AdminUserCreateView.as_view(), name="user_create"),
    path("users/<int:pk>/", AdminUserUpdateView.as_view(), name="user_update"),
    path("users/<int:pk>/delete/", AdminUserDeleteView.as_view(), name="user_delete"),
]
