# Generated by Django 5.2.16 on 2026-08-26 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import spaces.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reservations", "0004_reservation_attendee_count_reservation_notes_and_more"),
        ("spaces", "0007_atributos_icones"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="Nome"),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Uma frase explicando o que o usuário recebe ao solicitar.",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Agrupa os serviços na tela de reserva. Opcional.",
                        max_length=60,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        help_text="Nome de um ícone do catálogo da aplicação. Decoração apenas.",
                        max_length=40,
                        validators=[spaces.validators.validar_nome_de_icone],
                        verbose_name="Ícone",
                    ),
                ),
                (
                    "min_lead_time_hours",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Quantas horas antes do início da reserva o pedido precisa chegar. Zero significa sem exigência.",
                        verbose_name="Antecedência mínima",
                    ),
                ),
                (
                    "requires_notes",
                    models.BooleanField(
                        default=False,
                        help_text="Quando ligado, o usuário precisa descrever o que precisa antes de solicitar.",
                        verbose_name="Exige detalhamento",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Menor aparece primeiro. Empate resolve por nome.",
                        verbose_name="Ordem",
                    ),
                ),
                (
                    "spaces",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Onde este serviço é oferecido. Sem nenhum espaço marcado, ele não aparece para ninguém.",
                        related_name="services",
                        to="spaces.space",
                        verbose_name="Espaços",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de serviço",
                "verbose_name_plural": "Tipos de serviço",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ReservationServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Solicitado"),
                            ("acknowledged", "Recebido"),
                            ("in_progress", "Em andamento"),
                            ("completed", "Concluído"),
                            ("declined", "Recusado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="requested",
                        max_length=20,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="O que o usuário descreveu ao solicitar.",
                        verbose_name="Detalhamento",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Atendido em"),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_service_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atendido por",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_requests",
                        to="reservations.reservation",
                        verbose_name="Reserva",
                    ),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="services.servicetype",
                        verbose_name="Serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de serviço",
                "verbose_name_plural": "Solicitações de serviço",
                "ordering": ["reservation__start_time", "service_type__sort_order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reservation", "service_type"),
                        name="unique_service_request_per_reservation",
                    )
                ],
            },
        ),
    ]
