# Generated by Django 5.2.16 on 2026-08-26 04:38

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opening_time",
                    models.TimeField(
                        default=datetime.time(8, 0),
                        help_text="Primeiro horário do dia em que um espaço pode ser reservado.",
                        verbose_name="Abertura",
                    ),
                ),
                (
                    "closing_time",
                    models.TimeField(
                        default=datetime.time(18, 0),
                        help_text="Horário em que o último período de reserva termina.",
                        verbose_name="Fechamento",
                    ),
                ),
                (
                    "slot_minutes",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="De quantos em quantos minutos os horários são oferecidos.",
                        verbose_name="Incremento",
                    ),
                ),
                (
                    "min_duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="Menor reserva possível, em minutos.",
                        verbose_name="Duração mínima",
                    ),
                ),
                (
                    "max_duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=240,
                        help_text="Maior reserva possível, em minutos.",
                        verbose_name="Duração máxima",
                    ),
                ),
                (
                    "horizon_days",
                    models.PositiveSmallIntegerField(
                        default=90,
                        help_text="Com quantos dias de antecedência é possível reservar.",
                        verbose_name="Horizonte",
                    ),
                ),
                (
                    "few_slots_threshold",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Com esta quantidade de horários livres ou menos, o espaço é sinalizado como quase cheio.",
                        verbose_name="Limiar de “poucos horários”",
                    ),
                ),
                (
                    "enforce_window",
                    models.BooleanField(
                        default=False,
                        help_text="Quando ligado, uma reserva fora do horário de funcionamento ou fora dos limites de duração é recusada na gravação — inclusive pela API. Deixe desligado até revisar as reservas já existentes.",
                        verbose_name="Recusar reservas fora da janela",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Política de reserva",
                "verbose_name_plural": "Política de reserva",
            },
        ),
    ]
