# Generated by Django 5.2.16 on 2026-08-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_bookingpolicy_padrao"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="attendee_count",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Quantas pessoas devem comparecer.",
                null=True,
                verbose_name="Participantes",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Qualquer coisa que a administração precise saber. Opcional.",
                verbose_name="Observações",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Como esta reserva aparece para você e para a administração.",
                max_length=160,
                verbose_name="Assunto",
            ),
        ),
    ]
