# Generated by Django 5.2.16 on 2026-08-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0005_alter_reservation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpolicy",
            name="no_show_threshold_minutes",
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text="Quantos minutos depois do início a reserva ainda espera pelo check-in antes de ser liberada.",
                verbose_name="Tolerância para o check-in",
            ),
        ),
        migrations.AddField(
            model_name="bookingpolicy",
            name="release_no_shows",
            field=models.BooleanField(
                default=False,
                help_text="Quando ligado, uma reserva confirmada sem check-in é marcada como não comparecida depois da tolerância abaixo, e o espaço volta a ficar livre. Deixe desligado até a rotina de check-in estar no hábito de quem reserva — caso contrário, reservas legítimas serão liberadas.",
                verbose_name="Liberar reservas sem check-in",
            ),
        ),
    ]
