# Generated by Django 5.2.16 on 2026-08-28 18:49

"""Quando o cancelamento aconteceu.

Antes desta coluna, "cancelamentos no período" só podia ser respondido pelo
horário da reserva cancelada — que é uma pergunta diferente ("quanta sala foi
liberada") e a única que o histórico permite.

As reservas já canceladas ficam com ``cancelled_at`` nulo, **de propósito**. A
tentação é preenchê-las a partir de ``updated_at``, mas esse campo é
``auto_now`` e se move a cada gravação posterior: uma reserva cancelada em maio
e tocada em agosto apareceria como cancelada em agosto. Datas com cara de
verdadeiras são piores do que ausência de dado, e o relatório sabe tratar o
nulo — ver ``Reservation.objects.canceladas_entre``.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0007_dias_de_funcionamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Quando o cancelamento foi registrado.",
                null=True,
                verbose_name="Cancelada em",
            ),
        ),
    ]
