# Generated by Django 5.2.14 on 2026-05-07 22:49

from django.db import migrations


def enable_btree_gist(apps, schema_editor):
    """Enable the btree_gist extension on PostgreSQL."""
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")


class Migration(migrations.Migration):
    """Enable the btree_gist PostgreSQL extension."""

    dependencies = [
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(enable_btree_gist, migrations.RunPython.noop),
    ]
