# Generated by Django 5.2.16 on 2026-08-26 03:46

from django.db import migrations, models

import spaces.images
import spaces.validators


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0002_enable_btree_gist"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="JPG, PNG ou WebP. Mínimo 800x450 px, máximo 5 MB. A imagem é recortada em 16:9 nos cards.",
                null=True,
                upload_to=spaces.images.caminho_da_capa,
                validators=[spaces.validators.validar_imagem_de_capa],
                verbose_name="Imagem de capa",
            ),
        ),
    ]
