# Generated by Django 5.2.16 on 2026-08-26 04:17

import django.db.models.deletion
from django.db import migrations, models

import spaces.validators


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0003_space_cover_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpaceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=80, unique=True, verbose_name="Nome"),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        help_text="Nome de um ícone do catálogo da aplicação.",
                        max_length=40,
                        validators=[spaces.validators.validar_nome_de_icone],
                        verbose_name="Ícone",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Define a ordem das abas. Menor aparece primeiro.",
                        verbose_name="Ordem",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Tipo de espaço",
                "verbose_name_plural": "Tipos de espaço",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="space",
            name="space_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="spaces",
                to="spaces.spacetype",
                verbose_name="Tipo de espaço",
            ),
        ),
    ]
