# Generated by Django 5.2.16 on 2026-08-26 13:58

from django.db import migrations, models

import spaces.validators


class Migration(migrations.Migration):
    dependencies = [
        ("spaces", "0005_spacetype_catalogo_inicial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attribute",
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.AddField(
            model_name="attribute",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Agrupa os equipamentos na lista longa. Opcional.",
                max_length=60,
                verbose_name="Categoria",
            ),
        ),
        migrations.AddField(
            model_name="attribute",
            name="icon_name",
            field=models.CharField(
                blank=True,
                help_text="Nome de um ícone do catálogo da aplicação. Decoração apenas.",
                max_length=40,
                validators=[spaces.validators.validar_nome_de_icone],
                verbose_name="Ícone",
            ),
        ),
        migrations.AddField(
            model_name="attribute",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Aparece como filtro de primeira linha na busca por espaços.",
                verbose_name="Em destaque",
            ),
        ),
        migrations.AddField(
            model_name="attribute",
            name="sort_order",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Menor aparece primeiro. Empate resolve por nome.",
                verbose_name="Ordem",
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nome"),
        ),
    ]
