"""Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import urllib.parse
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-llv6qf^0%_=6#waw&oz+%_f=u-=1o6+j41u&59nlr2(83v&*j-",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() in ("1", "true", "yes", "on")

ALLOWED_HOSTS = [
    host.strip() for host in os.environ.get("ALLOWED_HOSTS", "").split(",") if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "django_filters",
    "django_htmx",
    "drf_yasg",
    "django_tailwind_cli",
    "accounts",
    "admin_dashboard",
    "core",
    "spaces",
    "reservations",
    "services",
    "ai_assistant",
    "knowledge",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise serve os arquivos estáticos direto do processo da aplicação, logo
    # depois do SecurityMiddleware, que é a posição exigida pela documentação.
    # É o que dispensa um nginx só para servir CSS, fontes e o htmx local.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

database_url = os.environ.get("DATABASE_URL")
if database_url:
    parsed_url = urllib.parse.urlparse(database_url)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": parsed_url.path[1:],
            "USER": parsed_url.username,
            "PASSWORD": parsed_url.password,
            "HOST": parsed_url.hostname,
            "PORT": str(parsed_url.port or "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

# Fuso oficial da operação (MPGO, Goiás). Os instantes continuam armazenados em
# UTC pelo PostgreSQL — TIME_ZONE define apenas como datas/horas informadas pelo
# usuário são interpretadas e como são exibidas.
TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Fontes dos estáticos, versionadas no repositório.
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Destino do `collectstatic`. Precisa ficar FORA de STATICFILES_DIRS, senão o
# Django coleta a saída da coleta anterior a cada execução.
STATIC_ROOT = BASE_DIR / "staticfiles"

# Uploads de usuário. O diretório é um volume nomeado em produção — o dump do
# Postgres não recupera arquivo perdido.
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Em desenvolvimento e nos testes o STATIC_ROOT não existe (só é preenchido pelo
# collectstatic, durante o build da imagem). Sem isto o WhiteNoise emite um aviso
# por requisição e tenta mapear um diretório ausente.
WHITENOISE_AUTOREFRESH = DEBUG

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # Em desenvolvimento o Django serve os arquivos direto de STATICFILES_DIRS.
        # Em produção o WhiteNoise comprime e versiona por hash, o que permite
        # cache imutável — e falha alto se um arquivo referenciado não existir,
        # em vez de servir um 404 silencioso.
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework
# https://www.django-rest-framework.org/

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
}

# Segurança em produção
# https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
#
# Só entra em vigor com DEBUG desligado, para não atrapalhar o desenvolvimento
# local (onde não há HTTPS e um redirect para https quebraria tudo).
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

if not DEBUG:
    if SECRET_KEY.startswith("django-insecure-"):
        raise ImproperlyConfigured(
            "SECRET_KEY não foi definida. Configure a variável de ambiente SECRET_KEY "
            "antes de rodar com DEBUG desligado."
        )

    # TLS geralmente termina no proxy à frente da aplicação; sem este cabeçalho o
    # Django acha que a requisição é http e entra em loop de redirect.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "True").lower() in (
        "1",
        "true",
        "yes",
        "on",
    )

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # 1 ano. Comece com um valor baixo e aumente depois de confirmar que todo o
    # domínio responde em HTTPS — HSTS não é reversível no navegador do usuário.
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", 60 * 60 * 24 * 365))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_HTTPONLY = True
    X_FRAME_OPTIONS = "DENY"


# Authentication redirects
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/spaces/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# AI services (Groq LLM)
# https://console.groq.com/docs/overview
GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")
GROQ_MODEL = os.environ.get("GROQ_MODEL", "openai/gpt-oss-120b")

# Base de conhecimento e RAG
# Corpus documental em data/normas/, indexado com pgvector.
KNOWLEDGE_DOCUMENTS_DIR = BASE_DIR / "data" / "normas"

# Modelo de embedding executado localmente via fastembed (ONNX, sem chave de API).
# ATENÇÃO: trocar por um modelo com dimensionalidade diferente exige nova migration,
# porque VectorField fixa as dimensões no schema.
EMBEDDING_MODEL = os.environ.get(
    "EMBEDDING_MODEL",
    "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
)
EMBEDDING_DIMENSIONS = int(os.environ.get("EMBEDDING_DIMENSIONS", "384"))

# Segmentação dos documentos, em caracteres.
CHUNK_SIZE = int(os.environ.get("CHUNK_SIZE", "1000"))
CHUNK_OVERLAP = int(os.environ.get("CHUNK_OVERLAP", "200"))

# Quantidade de trechos recuperados por consulta.
RAG_TOP_K = int(os.environ.get("RAG_TOP_K", "5"))

# Tailwind CSS (django-tailwind-cli) — no Node.js needed, downloads its own
# standalone binary. DaisyUI is enabled via TAILWIND_CLI_USE_DAISY_UI and the
# custom "mpgo" theme (cores institucionais do MPGO) is defined directly in
# TAILWIND_CLI_SRC_CSS.
# https://django-tailwind-cli.readthedocs.io/
TAILWIND_CLI_VERSION = "2.8.3"
TAILWIND_CLI_SRC_CSS = "assets/css/source.css"
TAILWIND_CLI_USE_DAISY_UI = True

# Logging
# https://docs.djangoproject.com/en/5.2/topics/logging/
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.environ.get("DJANGO_LOG_LEVEL", "INFO"),
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.environ.get("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "ai_assistant": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
